/* FLOWER		
	------------------------
	FLOWER_NAME : VARCHAR2(200),
	COLOR : VARCHAR2(100),
	PRICE : NUMBER,
	CONSTRAINT PRIMARY KEY(FLOWER_NAME)
	*/
DROP TABLE FLOWER;

CREATE TABLE FLOWER(
	FLOWERNAME VARCHAR2(200),
	FLOWERCOLOR VARCHAR2(100),
	FLOWERPRICE NUMBER,
	CONSTRAINT FLOWER_PK PRIMARY KEY(FLOWERNAME)
);
SELECT * FROM FLOWER;

/*POT
	-------------------------
	POT_ID : VARCHAR2(100),
	POT_COLOR : VARCHAR2(100),
	SHAPE : VARCHAR2(200),
	FLOWER_NAME : VARCHAR2(200)
	--------------------------
	CONSTRAINT FOREIGN KEY(FLOWER_NAME) REFERENCES FLOWER(FLOWER_NAME)
*/
DROP TABLE POT;

CREATE TABLE POT(
	POTID VARCHAR2(100),
	POTCOLOR VARCHAR2(100),
	POTSHAPE VARCHAR2(200),
	NAME VARCHAR2(200),
	CONSTRAINT POT_PK PRIMARY KEY(POTID),
	CONSTRAINT POT_FK FOREIGN KEY(NAME) REFERENCES FLOWER(FLOWERNAME)
);
SELECT * FROM POT;

