--GROUP BY : ~별(예 : 포지션 별 평균 키)
--SELECT ??? FROM ???
--WHERE 조건식
--GROUP BY 컬럼명
--HAVING 조건식

--PLAYER 테이블에서 포지션 검색
SELECT "POSITION" FROM PLAYER
GROUP BY "POSITION"
HAVING "POSITION" IS NOT NULL;

--WHERE 절에서 조건을 처리할 수 있다면 반드시 WHERE절에서 먼저 처리해준다.
SELECT "POSITION" FROM PLAYER
WHERE "POSITION" IS NOT NULL
GROUP BY "POSITION";

--PLAYER 테이블에서 몸무게가 80이상인 선수들의 평균 키가 180이상인 포지션 검색
SELECT "POSITION", AVG(HEIGHT), MIN(WEIGHT) FROM PLAYER
WHERE WEIGHT >= 80 
GROUP BY "POSITION"
HAVING AVG(HEIGHT) >= 180;

--SUB QUERY
--FROM절 : IN LINE VIEW
--SELECT절 : SCALAR
--WHERE절 : SUB QUERY

--PLAYER 테이블에서 TEAM_ID가 'K01'인 선수 중 POSITION이 'GK'인 선수
SELECT * FROM 
(
	SELECT * FROM PLAYER WHERE TEAM_ID = 'K01'	
)
WHERE "POSITION" = 'GK';

SELECT * FROM PLAYER WHERE TEAM_ID = 'K01' AND "POSITION" = 'GK';

--PLAYER 테이블에서 평균 키보다 작은 선수 검색
SELECT AVG(HEIGHT) FROM PLAYER;

SELECT * FROM PLAYER
WHERE HEIGHT < (SELECT AVG(HEIGHT) FROM PLAYER);

--PLAYER 테이블에서 전체 평균 키와 포지션별 평균 키 구하기
SELECT "POSITION", AVG(HEIGHT),(SELECT AVG(HEIGHT) FROM PLAYER) FROM PLAYER
WHERE "POSITION" IS NOT NULL
GROUP BY "POSITION";

--CASE 문으로 변경
SELECT
	ROUND(AVG(CASE "POSITION" WHEN 'GK' THEN HEIGHT END), 2) AS GK,
	ROUND(AVG(CASE "POSITION" WHEN 'DF' THEN HEIGHT END), 2) AS DF,
	ROUND(AVG(CASE "POSITION" WHEN 'FW' THEN HEIGHT END), 2) AS FW,
	ROUND(AVG(CASE "POSITION" WHEN 'MF' THEN HEIGHT END), 2) AS MF,
	ROUND(AVG(HEIGHT), 2) AS "전체평균"
FROM PLAYER;


--PLAYER 테이블에서 NICKNAME이 NULL인 선수들은 정태민 선수의 닉네임으로 바꾸기
SELECT NICKNAME FROM PLAYER WHERE PLAYER_NAME = '정태민';

UPDATE PLAYER
SET NICKNAME =(SELECT NICKNAME FROM PLAYER WHERE PLAYER_NAME = '정태민')
WHERE NICKNAME IS NULL;

SELECT * FROM PLAYER WHERE NICKNAME = '킹카';

--EMPLOYEES 테이블에서 평균 급여보다 낮은 사뤈들의 급여를 10%인상
SELECT AVG(SALARY) FROM EMPLOYEES; --6461.83
SELECT * FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES); --BRUCE

UPDATE EMPLOYEES
SET SALARY = SALARY * 1.1
WHERE SALARY <(SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT * FROM EMPLOYEES;

--PLAYER 테이블에서 평균 키보다 큰 선수들을 삭제
DELETE FROM PLAYER
WHERE HEIGHT > (SELECT AVG(HEIGHT) FROM PLAYER);

SELECT AVG(HEIGHT) FROM PLAYER; --179.31
SELECT MAX(HEIGHT) FROM PLAYER;